### ISSUE TITLE
make finder methods always available 

### ISSUE THREAD

**Issue by bumi** [kangguru/mad_id#4]
currently find_by_mad_id! is only available on models that use some identifier. 
In a project I have some models that use identifiers and some that don't. 

If we include the finder methods in ActiveRecord::Base and simply decide on the column to search for (id vs. identifier) we have a consitent API across all classes - and we could always use find_by_mad_id no matter what column we use.
That's what I did back in the https://github.com/bumi/find_by_param days. 

what do you think?

**Comment by kangguru** [comment]
this is then done in #5 correct?

**Comment by bumi** [comment]
yep
